### ISSUE TITLE
leniency on requirements

### ISSUE THREAD

**Issue by syre** [marten-cz/loco-cli#12]
I'm getting this on installation: `loco-cli 0.1.1 has requirement requests==2.10.0, but you'll have requests 2.19.1 which is incompatible.`

Perhaps we could add a bit of leniency to requirements versions?

**Comment by marten-cz** [comment]
Good idea. I'll update that. Hope that 2.* would be ok. There is nothing special used from these libraries, so there shouldn't be any break.

**Comment by syre** [comment]
I agree!

**Comment by marten-cz** [comment]
Fixed and new package deployed. Please test, if there will be any problem, let me know. By the way, the latest package was 0.2.2, now it's 0.2.3. I didn't update the dependencies for 0.1.*
