### ISSUE TITLE
Invalid exit codes

### ISSUE THREAD

**Issue by veewee** [marten-cz/loco-cli#15]
Both the pull and push command return exit code 1 on success meaning the command failed.
Could this be changed to exit code 0 ?

```sh
$ loco-cli pull --config loco.yaml
> Successfully pulled 1 file(s) from Localise.biz!
$ echo $?
> 1
```

```sh
$ loco-cli push --config loco.yaml
> Successfully pushed 1 file(s) to Localise.biz!
$ echo $?
> 1
```

**Comment by syre** [comment]
shouldn't #16 be sufficient?

**Comment by veewee** [comment]
Hi @syre,
Thanks for the feedback.
However, I don't know the codebase nor python, so I don't know if the code results in 0 exit codes for successful commands.
I winded up writing a custom cli tool since there were also some other additional features I wanted.

**Comment by syre** [comment]
@veewee alright no problem, @marten-cz perhaps you can take a look.

**Comment by marten-cz** [comment]
Thanks for the report, I'll try to have a look at this weekend. I'll have a look at the #16 , maybe it will be enough.

**Comment by marten-cz** [comment]
@syre I just updated what you did and added the sys.exit to all possible places where required.

@veewee Please have a look, version 0.2.5rc1

**Comment by marten-cz** [comment]
Closing, should be ok. No reports that it's not working.
