### ISSUE TITLE
loco-cli tool entry point script not working in Python3

### ISSUE THREAD

**Issue by syre** [marten-cz/loco-cli#8]
While the regular `localise.py` script works, i found the `loco-cli` entry point script does not seem to work with Python3, probably related to disabling relative imports in Python3:
```
Traceback (most recent call last):
  File "/home/syre/.local/bin/loco-cli", line 7, in <module>
    from localise.localise import main
  File "/home/syre/.local/lib/python3.6/site-packages/localise/localise.py", line 7, in <module>
    from commands import *
ModuleNotFoundError: No module named 'commands'
```

**Comment by marten-cz** [comment]
Yep, most likely. Will try to fix that today.

**Comment by marten-cz** [comment]
Fixed. Tried that  with both version, and in development and as package. Maybe not best solution, but it's working. Created new version 0.2.1
